/**
 * Shared loading logic for the scroll-scrub film (see ScrollFilm.tsx and
 * FILM_GUIDE.md). The film exists once `public/film/manifest.json` is
 * generated by `scripts/convert-film.mjs`; until then everything here
 * resolves to "no film" and the section stays hidden.
 */

export interface FilmManifest {
  frameCount: number;
  width: number;
  height: number;
  fps?: number;
}

const base = import.meta.env.BASE_URL;

export const loFrameUrl = (n: number) =>
  `${base}film/lo/${String(n).padStart(4, '0')}.webp`;
export const hiFrameUrl = (n: number) =>
  `${base}film/hi/${String(n).padStart(4, '0')}.webp`;

let manifest: FilmManifest | null = null;
let manifestPromise: Promise<FilmManifest | null> | null = null;

export function getFilmManifest(): FilmManifest | null {
  return manifest;
}

/** Fetches manifest.json once; resolves null when no film has been added. */
export function loadFilmManifest(): Promise<FilmManifest | null> {
  if (!manifestPromise) {
    manifestPromise = fetch(`${base}film/manifest.json`)
      .then(async (res) => {
        if (!res.ok) return null;
        // Dev/preview servers answer missing files with the SPA's index.html;
        // only trust a JSON response.
        if (!(res.headers.get('content-type') || '').includes('json')) return null;
        const data = await res.json();
        if (typeof data?.frameCount !== 'number' || data.frameCount < 2) return null;
        manifest = data as FilmManifest;
        return manifest;
      })
      .catch(() => null);
  }
  return manifestPromise;
}

let loPromise: Promise<(HTMLImageElement | null)[]> | null = null;

/** Preloads and keeps every lo-tier frame decoded; idempotent. */
export function preloadLoTier(m: FilmManifest): Promise<(HTMLImageElement | null)[]> {
  if (!loPromise) {
    loPromise = Promise.all(
      Array.from({ length: m.frameCount }, (_, i) => {
        return new Promise<HTMLImageElement | null>((resolve) => {
          const img = new Image();
          img.onload = () => resolve(img);
          img.onerror = () => resolve(null);
          img.src = loFrameUrl(i + 1);
        });
      }),
    );
  }
  return loPromise;
}

/**
 * Called behind the intro seal: if a film exists, warm the lo tier so
 * scrubbing never stutters. Never rejects.
 */
export async function preloadFilmIfPresent(): Promise<void> {
  const m = await loadFilmManifest();
  if (m) await preloadLoTier(m).then(() => undefined);
}
